---
title: Afterschool Maryland
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    categories: ''
    ages-served: ''
    services-provided: ''
    is-free: ''
    featured-thumbnail-image: ''
    featured-image: ''
    permalink: "/:title"
    description: ''
    point-of-contact: ''
    phone-number: ''
    phone-ext: ''
    email-address: ''
    street-address: ''
    city-state-zip: ''
    website: ''
- scope:
    path: index.html
  values:
    body_class: show_hero_search
url: https://www.afterschoolmaryland.com
baseurl:
email:
description: Afterschool Maryland is an online database of afterschool programs in
  Montgomery County & throughout Maryland. Search for youth programs and apply online.
logo:
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-archives
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
jekyll-archives:
  enabled:
  - categories
types:
- Document
- Video
