---
title: Base
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    categories: ''
    featured-image: ''
    permalink: "/:categories/:title"
    description: ''
    phone-number: ''
    street-address: ''
    city-state-zip: ''
- scope:
    path: index.html
  values:
    body_class: show_hero_search
url: https://rhyanvargas.github.io/after-school-web-app
baseurl: 
email: 
description: Knowledge base template for Jekyll.
logo: "/uploads/siteicon.png"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-archives
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
jekyll-archives:
  enabled:
  - categories
types:
- Document
- Video
